// Japanese Journey V5.2 — curated development curriculum.
// Catatan: JLPT tidak menyediakan daftar kosakata/kanji resmi lengkap per level; data ini adalah kurikulum pengembangan terstruktur, bukan klaim daftar resmi JLPT.
const parseKana=(type,group,s)=>s.split(',').map(x=>{const [character,romaji]=x.split(':');return {type,group,character,romaji}});
export const kana = [
  ...parseKana("hiragana","basic","あ:a,い:i,う:u,え:e,お:o,か:ka,き:ki,く:ku,け:ke,こ:ko,さ:sa,し:shi,す:su,せ:se,そ:so,た:ta,ち:chi,つ:tsu,て:te,と:to,な:na,に:ni,ぬ:nu,ね:ne,の:no,は:ha,ひ:hi,ふ:fu,へ:he,ほ:ho,ま:ma,み:mi,む:mu,め:me,も:mo,や:ya,ゆ:yu,よ:yo,ら:ra,り:ri,る:ru,れ:re,ろ:ro,わ:wa,を:wo,ん:n"),
  ...parseKana("hiragana","dakuten","が:ga,ぎ:gi,ぐ:gu,げ:ge,ご:go,ざ:za,じ:ji,ず:zu,ぜ:ze,ぞ:zo,だ:da,ぢ:ji,づ:zu,で:de,ど:do,ば:ba,び:bi,ぶ:bu,べ:be,ぼ:bo"),
  ...parseKana("hiragana","handakuten","ぱ:pa,ぴ:pi,ぷ:pu,ぺ:pe,ぽ:po"),
  ...parseKana("hiragana","yoon","きゃ:kya,きゅ:kyu,きょ:kyo,しゃ:sha,しゅ:shu,しょ:sho,ちゃ:cha,ちゅ:chu,ちょ:cho,にゃ:nya,にゅ:nyu,にょ:nyo,ひゃ:hya,ひゅ:hyu,ひょ:hyo,みゃ:mya,みゅ:myu,みょ:myo,りゃ:rya,りゅ:ryu,りょ:ryo,ぎゃ:gya,ぎゅ:gyu,ぎょ:gyo,じゃ:ja,じゅ:ju,じょ:jo,びゃ:bya,びゅ:byu,びょ:byo,ぴゃ:pya,ぴゅ:pyu,ぴょ:pyo"),
  ...parseKana("katakana","basic","ア:a,イ:i,ウ:u,エ:e,オ:o,カ:ka,キ:ki,ク:ku,ケ:ke,コ:ko,サ:sa,シ:shi,ス:su,セ:se,ソ:so,タ:ta,チ:chi,ツ:tsu,テ:te,ト:to,ナ:na,ニ:ni,ヌ:nu,ネ:ne,ノ:no,ハ:ha,ヒ:hi,フ:fu,ヘ:he,ホ:ho,マ:ma,ミ:mi,ム:mu,メ:me,モ:mo,ヤ:ya,ユ:yu,ヨ:yo,ラ:ra,リ:ri,ル:ru,レ:re,ロ:ro,ワ:wa,ヲ:wo,ン:n"),
  ...parseKana("katakana","dakuten","ガ:ga,ギ:gi,グ:gu,ゲ:ge,ゴ:go,ザ:za,ジ:ji,ズ:zu,ゼ:ze,ゾ:zo,ダ:da,ヂ:ji,ヅ:zu,デ:de,ド:do,バ:ba,ビ:bi,ブ:bu,ベ:be,ボ:bo"),
  ...parseKana("katakana","handakuten","パ:pa,ピ:pi,プ:pu,ペ:pe,ポ:po"),
  ...parseKana("katakana","yoon","キャ:kya,キュ:kyu,キョ:kyo,シャ:sha,シュ:shu,ショ:sho,チャ:cha,チュ:chu,チョ:cho,ニャ:nya,ニュ:nyu,ニョ:nyo,ヒャ:hya,ヒュ:hyu,ヒョ:hyo,ミャ:mya,ミュ:myu,ミョ:myo,リャ:rya,リュ:ryu,リョ:ryo,ギャ:gya,ギュ:gyu,ギョ:gyo,ジャ:ja,ジュ:ju,ジョ:jo,ビャ:bya,ビュ:byu,ビョ:byo,ピャ:pya,ピュ:pyu,ピョ:pyo"),
];

export const vocab = [
  {"word":"私","reading":"わたし","romaji":"watashi","meaning":"saya","level":"N5","category":"People"},
  {"word":"あなた","reading":"あなた","romaji":"anata","meaning":"kamu / Anda","level":"N5","category":"People"},
  {"word":"人","reading":"ひと","romaji":"hito","meaning":"orang","level":"N5","category":"People"},
  {"word":"友達","reading":"ともだち","romaji":"tomodachi","meaning":"teman","level":"N5","category":"People"},
  {"word":"家族","reading":"かぞく","romaji":"kazoku","meaning":"keluarga","level":"N5","category":"People"},
  {"word":"先生","reading":"せんせい","romaji":"sensei","meaning":"guru","level":"N5","category":"School"},
  {"word":"学生","reading":"がくせい","romaji":"gakusei","meaning":"pelajar / mahasiswa","level":"N5","category":"School"},
  {"word":"学校","reading":"がっこう","romaji":"gakkou","meaning":"sekolah","level":"N5","category":"School"},
  {"word":"大学","reading":"だいがく","romaji":"daigaku","meaning":"universitas","level":"N5","category":"School"},
  {"word":"本","reading":"ほん","romaji":"hon","meaning":"buku","level":"N5","category":"School"},
  {"word":"日本","reading":"にほん","romaji":"nihon","meaning":"Jepang","level":"N5","category":"Places"},
  {"word":"国","reading":"くに","romaji":"kuni","meaning":"negara","level":"N5","category":"Places"},
  {"word":"家","reading":"いえ","romaji":"ie","meaning":"rumah","level":"N5","category":"Places"},
  {"word":"駅","reading":"えき","romaji":"eki","meaning":"stasiun","level":"N5","category":"Transportation"},
  {"word":"電車","reading":"でんしゃ","romaji":"densha","meaning":"kereta","level":"N5","category":"Transportation"},
  {"word":"車","reading":"くるま","romaji":"kuruma","meaning":"mobil","level":"N5","category":"Transportation"},
  {"word":"今日","reading":"きょう","romaji":"kyou","meaning":"hari ini","level":"N5","category":"Time"},
  {"word":"明日","reading":"あした","romaji":"ashita","meaning":"besok","level":"N5","category":"Time"},
  {"word":"昨日","reading":"きのう","romaji":"kinou","meaning":"kemarin","level":"N5","category":"Time"},
  {"word":"朝","reading":"あさ","romaji":"asa","meaning":"pagi","level":"N5","category":"Time"},
  {"word":"昼","reading":"ひる","romaji":"hiru","meaning":"siang","level":"N5","category":"Time"},
  {"word":"夜","reading":"よる","romaji":"yoru","meaning":"malam","level":"N5","category":"Time"},
  {"word":"時間","reading":"じかん","romaji":"jikan","meaning":"waktu / jam","level":"N5","category":"Time"},
  {"word":"水","reading":"みず","romaji":"mizu","meaning":"air","level":"N5","category":"Food"},
  {"word":"ご飯","reading":"ごはん","romaji":"gohan","meaning":"nasi / makanan","level":"N5","category":"Food"},
  {"word":"食べる","reading":"たべる","romaji":"taberu","meaning":"makan","level":"N5","category":"Daily Life"},
  {"word":"飲む","reading":"のむ","romaji":"nomu","meaning":"minum","level":"N5","category":"Daily Life"},
  {"word":"見る","reading":"みる","romaji":"miru","meaning":"melihat","level":"N5","category":"Daily Life"},
  {"word":"聞く","reading":"きく","romaji":"kiku","meaning":"mendengar / bertanya","level":"N5","category":"Daily Life"},
  {"word":"読む","reading":"よむ","romaji":"yomu","meaning":"membaca","level":"N5","category":"Daily Life"},
  {"word":"書く","reading":"かく","romaji":"kaku","meaning":"menulis","level":"N5","category":"Daily Life"},
  {"word":"話す","reading":"はなす","romaji":"hanasu","meaning":"berbicara","level":"N5","category":"Daily Life"},
  {"word":"行く","reading":"いく","romaji":"iku","meaning":"pergi","level":"N5","category":"Travel"},
  {"word":"来る","reading":"くる","romaji":"kuru","meaning":"datang","level":"N5","category":"Travel"},
  {"word":"帰る","reading":"かえる","romaji":"kaeru","meaning":"pulang","level":"N5","category":"Travel"},
  {"word":"買う","reading":"かう","romaji":"kau","meaning":"membeli","level":"N5","category":"Shopping"},
  {"word":"大きい","reading":"おおきい","romaji":"ookii","meaning":"besar","level":"N5","category":"Adjective"},
  {"word":"小さい","reading":"ちいさい","romaji":"chiisai","meaning":"kecil","level":"N5","category":"Adjective"},
  {"word":"新しい","reading":"あたらしい","romaji":"atarashii","meaning":"baru","level":"N5","category":"Adjective"},
  {"word":"古い","reading":"ふるい","romaji":"furui","meaning":"lama / tua (benda)","level":"N5","category":"Adjective"},
  {"word":"必要","reading":"ひつよう","romaji":"hitsuyou","meaning":"perlu / diperlukan","level":"N4","category":"Daily Life"},
  {"word":"準備","reading":"じゅんび","romaji":"junbi","meaning":"persiapan","level":"N4","category":"Activities"},
  {"word":"予定","reading":"よてい","romaji":"yotei","meaning":"rencana / jadwal","level":"N4","category":"Time"},
  {"word":"最近","reading":"さいきん","romaji":"saikin","meaning":"akhir-akhir ini","level":"N4","category":"Time"},
  {"word":"経験","reading":"けいけん","romaji":"keiken","meaning":"pengalaman","level":"N4","category":"Work"},
  {"word":"説明","reading":"せつめい","romaji":"setsumei","meaning":"penjelasan","level":"N4","category":"School"},
  {"word":"練習","reading":"れんしゅう","romaji":"renshuu","meaning":"latihan","level":"N4","category":"School"},
  {"word":"質問","reading":"しつもん","romaji":"shitsumon","meaning":"pertanyaan","level":"N4","category":"School"},
  {"word":"答え","reading":"こたえ","romaji":"kotae","meaning":"jawaban","level":"N4","category":"School"},
  {"word":"試験","reading":"しけん","romaji":"shiken","meaning":"ujian","level":"N4","category":"School"},
  {"word":"仕事","reading":"しごと","romaji":"shigoto","meaning":"pekerjaan","level":"N4","category":"Work"},
  {"word":"会社","reading":"かいしゃ","romaji":"kaisha","meaning":"perusahaan","level":"N4","category":"Work"},
  {"word":"工場","reading":"こうじょう","romaji":"koujou","meaning":"pabrik","level":"N4","category":"Work"},
  {"word":"働く","reading":"はたらく","romaji":"hataraku","meaning":"bekerja","level":"N4","category":"Work"},
  {"word":"始める","reading":"はじめる","romaji":"hajimeru","meaning":"memulai","level":"N4","category":"Activities"},
  {"word":"続ける","reading":"つづける","romaji":"tsuzukeru","meaning":"melanjutkan","level":"N4","category":"Activities"},
  {"word":"終わる","reading":"おわる","romaji":"owaru","meaning":"selesai / berakhir","level":"N4","category":"Activities"},
  {"word":"決める","reading":"きめる","romaji":"kimeru","meaning":"memutuskan","level":"N4","category":"Activities"},
  {"word":"調べる","reading":"しらべる","romaji":"shiraberu","meaning":"mencari tahu / memeriksa","level":"N4","category":"Activities"},
  {"word":"手伝う","reading":"てつだう","romaji":"tetsudau","meaning":"membantu","level":"N4","category":"Activities"},
  {"word":"使う","reading":"つかう","romaji":"tsukau","meaning":"menggunakan","level":"N4","category":"Daily Life"},
  {"word":"作る","reading":"つくる","romaji":"tsukuru","meaning":"membuat","level":"N4","category":"Daily Life"},
  {"word":"持つ","reading":"もつ","romaji":"motsu","meaning":"membawa / memiliki","level":"N4","category":"Daily Life"},
  {"word":"待つ","reading":"まつ","romaji":"matsu","meaning":"menunggu","level":"N4","category":"Daily Life"},
  {"word":"急ぐ","reading":"いそぐ","romaji":"isogu","meaning":"bergegas","level":"N4","category":"Daily Life"},
  {"word":"間に合う","reading":"まにあう","romaji":"maniau","meaning":"tepat waktu","level":"N4","category":"Time"},
  {"word":"心配","reading":"しんぱい","romaji":"shinpai","meaning":"khawatir","level":"N4","category":"Feelings"},
  {"word":"安心","reading":"あんしん","romaji":"anshin","meaning":"lega / tenang","level":"N4","category":"Feelings"},
  {"word":"残念","reading":"ざんねん","romaji":"zannen","meaning":"sayang / disesalkan","level":"N4","category":"Feelings"},
  {"word":"便利","reading":"べんり","romaji":"benri","meaning":"praktis / nyaman","level":"N4","category":"Adjective"},
  {"word":"不便","reading":"ふべん","romaji":"fuben","meaning":"tidak praktis","level":"N4","category":"Adjective"},
  {"word":"安全","reading":"あんぜん","romaji":"anzen","meaning":"aman","level":"N4","category":"Safety"},
  {"word":"危険","reading":"きけん","romaji":"kiken","meaning":"berbahaya","level":"N4","category":"Safety"},
  {"word":"交通","reading":"こうつう","romaji":"koutsuu","meaning":"lalu lintas / transportasi","level":"N4","category":"Transportation"},
  {"word":"旅行","reading":"りょこう","romaji":"ryokou","meaning":"perjalanan / wisata","level":"N4","category":"Travel"},
  {"word":"予約","reading":"よやく","romaji":"yoyaku","meaning":"reservasi","level":"N4","category":"Travel"},
  {"word":"場所","reading":"ばしょ","romaji":"basho","meaning":"tempat","level":"N4","category":"Places"},
  {"word":"文化","reading":"ぶんか","romaji":"bunka","meaning":"budaya","level":"N4","category":"Society"},
  {"word":"生活","reading":"せいかつ","romaji":"seikatsu","meaning":"kehidupan sehari-hari","level":"N4","category":"Daily Life"},
  {"word":"習慣","reading":"しゅうかん","romaji":"shuukan","meaning":"kebiasaan","level":"N4","category":"Daily Life"},
  {"word":"技術","reading":"ぎじゅつ","romaji":"gijutsu","meaning":"teknologi / keterampilan teknis","level":"N3","category":"Technology"},
  {"word":"環境","reading":"かんきょう","romaji":"kankyou","meaning":"lingkungan","level":"N3","category":"Society"},
  {"word":"影響","reading":"えいきょう","romaji":"eikyou","meaning":"pengaruh / dampak","level":"N3","category":"Society"},
  {"word":"関係","reading":"かんけい","romaji":"kankei","meaning":"hubungan / relasi","level":"N3","category":"Society"},
  {"word":"改善","reading":"かいぜん","romaji":"kaizen","meaning":"perbaikan","level":"N3","category":"Work"},
  {"word":"生産","reading":"せいさん","romaji":"seisan","meaning":"produksi","level":"N3","category":"Work"},
  {"word":"品質","reading":"ひんしつ","romaji":"hinshitsu","meaning":"kualitas","level":"N3","category":"Work"},
  {"word":"管理","reading":"かんり","romaji":"kanri","meaning":"pengelolaan / manajemen","level":"N3","category":"Work"},
  {"word":"作業","reading":"さぎょう","romaji":"sagyou","meaning":"pekerjaan / operasi kerja","level":"N3","category":"Work"},
  {"word":"設備","reading":"せつび","romaji":"setsubi","meaning":"peralatan / fasilitas","level":"N3","category":"Work"},
  {"word":"確認","reading":"かくにん","romaji":"kakunin","meaning":"konfirmasi / pemeriksaan","level":"N3","category":"Work"},
  {"word":"報告","reading":"ほうこく","romaji":"houkoku","meaning":"laporan / melapor","level":"N3","category":"Work"},
  {"word":"連絡","reading":"れんらく","romaji":"renraku","meaning":"menghubungi / kontak","level":"N3","category":"Work"},
  {"word":"相談","reading":"そうだん","romaji":"soudan","meaning":"konsultasi / berdiskusi","level":"N3","category":"Work"},
  {"word":"対応","reading":"たいおう","romaji":"taiou","meaning":"penanganan / respons","level":"N3","category":"Work"},
  {"word":"原因","reading":"げんいん","romaji":"genin","meaning":"penyebab","level":"N3","category":"Reasoning"},
  {"word":"結果","reading":"けっか","romaji":"kekka","meaning":"hasil","level":"N3","category":"Reasoning"},
  {"word":"方法","reading":"ほうほう","romaji":"houhou","meaning":"cara / metode","level":"N3","category":"Reasoning"},
  {"word":"目的","reading":"もくてき","romaji":"mokuteki","meaning":"tujuan","level":"N3","category":"Reasoning"},
  {"word":"条件","reading":"じょうけん","romaji":"jouken","meaning":"syarat / kondisi","level":"N3","category":"Reasoning"},
  {"word":"場合","reading":"ばあい","romaji":"baai","meaning":"kasus / keadaan","level":"N3","category":"Reasoning"},
  {"word":"状況","reading":"じょうきょう","romaji":"joukyou","meaning":"situasi / kondisi","level":"N3","category":"Society"},
  {"word":"内容","reading":"ないよう","romaji":"naiyou","meaning":"isi / konten","level":"N3","category":"General"},
  {"word":"情報","reading":"じょうほう","romaji":"jouhou","meaning":"informasi","level":"N3","category":"Technology"},
  {"word":"資料","reading":"しりょう","romaji":"shiryou","meaning":"dokumen / materi referensi","level":"N3","category":"School"},
  {"word":"知識","reading":"ちしき","romaji":"chishiki","meaning":"pengetahuan","level":"N3","category":"School"},
  {"word":"能力","reading":"のうりょく","romaji":"nouryoku","meaning":"kemampuan","level":"N3","category":"General"},
  {"word":"努力","reading":"どりょく","romaji":"doryoku","meaning":"usaha","level":"N3","category":"General"},
  {"word":"成長","reading":"せいちょう","romaji":"seichou","meaning":"pertumbuhan / perkembangan","level":"N3","category":"General"},
  {"word":"成功","reading":"せいこう","romaji":"seikou","meaning":"keberhasilan","level":"N3","category":"General"},
  {"word":"失敗","reading":"しっぱい","romaji":"shippai","meaning":"kegagalan / kesalahan","level":"N3","category":"General"},
  {"word":"選択","reading":"せんたく","romaji":"sentaku","meaning":"pilihan / pemilihan","level":"N3","category":"General"},
  {"word":"判断","reading":"はんだん","romaji":"handan","meaning":"penilaian / keputusan","level":"N3","category":"Reasoning"},
  {"word":"必要性","reading":"ひつようせい","romaji":"hitsuyousei","meaning":"kebutuhan / pentingnya","level":"N3","category":"Reasoning"},
  {"word":"増加","reading":"ぞうか","romaji":"zouka","meaning":"peningkatan","level":"N3","category":"Society"},
  {"word":"減少","reading":"げんしょう","romaji":"genshou","meaning":"penurunan","level":"N3","category":"Society"},
  {"word":"変化","reading":"へんか","romaji":"henka","meaning":"perubahan","level":"N3","category":"General"},
  {"word":"比較","reading":"ひかく","romaji":"hikaku","meaning":"perbandingan","level":"N3","category":"Reasoning"},
  {"word":"一般","reading":"いっぱん","romaji":"ippan","meaning":"umum","level":"N3","category":"General"},
  {"word":"具体的","reading":"ぐたいてき","romaji":"gutaiteki","meaning":"konkret / spesifik","level":"N3","category":"Reasoning"},
];

export const kanji = [
  {"k":"日","meaning":"hari / matahari","on":"ニチ・ジツ","kun":"ひ・か","strokes":4,"radical":"日","level":"N5","examples":["日本","今日"]},
  {"k":"月","meaning":"bulan / bulan langit","on":"ゲツ・ガツ","kun":"つき","strokes":4,"radical":"月","level":"N5","examples":["月曜日","今月"]},
  {"k":"火","meaning":"api","on":"カ","kun":"ひ","strokes":4,"radical":"火","level":"N5","examples":["火曜日","火"]},
  {"k":"水","meaning":"air","on":"スイ","kun":"みず","strokes":4,"radical":"水","level":"N5","examples":["水曜日","水"]},
  {"k":"木","meaning":"pohon / kayu","on":"モク・ボク","kun":"き","strokes":4,"radical":"木","level":"N5","examples":["木曜日","木"]},
  {"k":"金","meaning":"emas / uang","on":"キン・コン","kun":"かね","strokes":8,"radical":"金","level":"N5","examples":["金曜日","お金"]},
  {"k":"土","meaning":"tanah","on":"ド・ト","kun":"つち","strokes":3,"radical":"土","level":"N5","examples":["土曜日","土地"]},
  {"k":"人","meaning":"orang","on":"ジン・ニン","kun":"ひと","strokes":2,"radical":"人","level":"N5","examples":["日本人","人"]},
  {"k":"本","meaning":"buku / asal","on":"ホン","kun":"もと","strokes":5,"radical":"木","level":"N5","examples":["日本","本"]},
  {"k":"学","meaning":"belajar","on":"ガク","kun":"まなぶ","strokes":8,"radical":"子","level":"N5","examples":["学生","学校"]},
  {"k":"校","meaning":"sekolah","on":"コウ","kun":"—","strokes":10,"radical":"木","level":"N5","examples":["学校"]},
  {"k":"先","meaning":"lebih dulu / sebelumnya","on":"セン","kun":"さき","strokes":6,"radical":"儿","level":"N5","examples":["先生","先"]},
  {"k":"生","meaning":"hidup / lahir","on":"セイ・ショウ","kun":"いきる・うまれる","strokes":5,"radical":"生","level":"N5","examples":["先生","学生"]},
  {"k":"食","meaning":"makan / makanan","on":"ショク","kun":"たべる","strokes":9,"radical":"食","level":"N5","examples":["食べる","食事"]},
  {"k":"飲","meaning":"minum","on":"イン","kun":"のむ","strokes":12,"radical":"食","level":"N5","examples":["飲む","飲み物"]},
  {"k":"見","meaning":"melihat","on":"ケン","kun":"みる","strokes":7,"radical":"見","level":"N5","examples":["見る","見学"]},
  {"k":"行","meaning":"pergi / menjalankan","on":"コウ・ギョウ","kun":"いく・おこなう","strokes":6,"radical":"行","level":"N5","examples":["行く","銀行"]},
  {"k":"来","meaning":"datang","on":"ライ","kun":"くる","strokes":7,"radical":"木","level":"N5","examples":["来る","来年"]},
  {"k":"車","meaning":"kendaraan / mobil","on":"シャ","kun":"くるま","strokes":7,"radical":"車","level":"N5","examples":["電車","車"]},
  {"k":"電","meaning":"listrik","on":"デン","kun":"—","strokes":13,"radical":"雨","level":"N5","examples":["電車","電話"]},
  {"k":"会","meaning":"bertemu / perkumpulan","on":"カイ","kun":"あう","strokes":6,"radical":"人","level":"N4","examples":["会社","会う"]},
  {"k":"社","meaning":"perusahaan / kuil","on":"シャ","kun":"やしろ","strokes":7,"radical":"示","level":"N4","examples":["会社","神社"]},
  {"k":"仕","meaning":"melayani / melakukan","on":"シ・ジ","kun":"つかえる","strokes":5,"radical":"人","level":"N4","examples":["仕事"]},
  {"k":"事","meaning":"hal / urusan","on":"ジ・ズ","kun":"こと","strokes":8,"radical":"亅","level":"N4","examples":["仕事","食事"]},
  {"k":"工","meaning":"kerja / teknik","on":"コウ・ク","kun":"—","strokes":3,"radical":"工","level":"N4","examples":["工場","工業"]},
  {"k":"場","meaning":"tempat","on":"ジョウ","kun":"ば","strokes":12,"radical":"土","level":"N4","examples":["工場","場所"]},
  {"k":"作","meaning":"membuat","on":"サク・サ","kun":"つくる","strokes":7,"radical":"人","level":"N4","examples":["作る","作業"]},
  {"k":"使","meaning":"menggunakan","on":"シ","kun":"つかう","strokes":8,"radical":"人","level":"N4","examples":["使う"]},
  {"k":"始","meaning":"memulai","on":"シ","kun":"はじめる・はじまる","strokes":8,"radical":"女","level":"N4","examples":["始める","開始"]},
  {"k":"終","meaning":"akhir / selesai","on":"シュウ","kun":"おわる","strokes":11,"radical":"糸","level":"N4","examples":["終わる","終了"]},
  {"k":"決","meaning":"memutuskan","on":"ケツ","kun":"きめる","strokes":7,"radical":"水","level":"N4","examples":["決める","決定"]},
  {"k":"予","meaning":"sebelumnya / rencana","on":"ヨ","kun":"—","strokes":4,"radical":"亅","level":"N4","examples":["予定","予約"]},
  {"k":"定","meaning":"menetapkan","on":"テイ・ジョウ","kun":"さだめる","strokes":8,"radical":"宀","level":"N4","examples":["予定","決定"]},
  {"k":"安","meaning":"aman / murah","on":"アン","kun":"やすい","strokes":6,"radical":"宀","level":"N4","examples":["安全","安心"]},
  {"k":"全","meaning":"seluruh / lengkap","on":"ゼン","kun":"まったく","strokes":6,"radical":"入","level":"N4","examples":["安全","全部"]},
  {"k":"危","meaning":"bahaya","on":"キ","kun":"あぶない","strokes":6,"radical":"卩","level":"N4","examples":["危険"]},
  {"k":"険","meaning":"curam / berbahaya","on":"ケン","kun":"けわしい","strokes":11,"radical":"阜","level":"N4","examples":["危険"]},
  {"k":"文","meaning":"tulisan / budaya","on":"ブン・モン","kun":"ふみ","strokes":4,"radical":"文","level":"N4","examples":["文化","文章"]},
  {"k":"化","meaning":"perubahan","on":"カ・ケ","kun":"ばける","strokes":4,"radical":"匕","level":"N4","examples":["文化","変化"]},
  {"k":"験","meaning":"uji / pengalaman","on":"ケン・ゲン","kun":"—","strokes":18,"radical":"馬","level":"N4","examples":["経験","試験"]},
  {"k":"技","meaning":"teknik / keterampilan","on":"ギ","kun":"わざ","strokes":7,"radical":"手","level":"N3","examples":["技術"]},
  {"k":"術","meaning":"teknik / seni","on":"ジュツ","kun":"すべ","strokes":11,"radical":"行","level":"N3","examples":["技術"]},
  {"k":"環","meaning":"lingkar / lingkungan","on":"カン","kun":"—","strokes":17,"radical":"玉","level":"N3","examples":["環境"]},
  {"k":"境","meaning":"batas / keadaan","on":"キョウ・ケイ","kun":"さかい","strokes":14,"radical":"土","level":"N3","examples":["環境"]},
  {"k":"影","meaning":"bayangan / pengaruh","on":"エイ","kun":"かげ","strokes":15,"radical":"彡","level":"N3","examples":["影響"]},
  {"k":"響","meaning":"gema / pengaruh","on":"キョウ","kun":"ひびく","strokes":20,"radical":"音","level":"N3","examples":["影響"]},
  {"k":"関","meaning":"hubungan / gerbang","on":"カン","kun":"せき","strokes":14,"radical":"門","level":"N3","examples":["関係"]},
  {"k":"係","meaning":"hubungan / petugas","on":"ケイ","kun":"かかる・かかり","strokes":9,"radical":"人","level":"N3","examples":["関係","係員"]},
  {"k":"改","meaning":"memperbaiki","on":"カイ","kun":"あらためる","strokes":7,"radical":"攵","level":"N3","examples":["改善"]},
  {"k":"善","meaning":"baik / kebaikan","on":"ゼン","kun":"よい","strokes":12,"radical":"口","level":"N3","examples":["改善"]},
  {"k":"生","meaning":"hidup / menghasilkan","on":"セイ・ショウ","kun":"いきる・うむ","strokes":5,"radical":"生","level":"N3","examples":["生産"]},
  {"k":"産","meaning":"produksi / melahirkan","on":"サン","kun":"うむ","strokes":11,"radical":"生","level":"N3","examples":["生産"]},
  {"k":"品","meaning":"barang / kualitas","on":"ヒン","kun":"しな","strokes":9,"radical":"口","level":"N3","examples":["品質"]},
  {"k":"質","meaning":"kualitas / sifat","on":"シツ・シチ","kun":"たち","strokes":15,"radical":"貝","level":"N3","examples":["品質","質問"]},
  {"k":"管","meaning":"pipa / mengelola","on":"カン","kun":"くだ","strokes":14,"radical":"竹","level":"N3","examples":["管理"]},
  {"k":"理","meaning":"alasan / mengatur","on":"リ","kun":"—","strokes":11,"radical":"玉","level":"N3","examples":["管理","理由"]},
  {"k":"報","meaning":"laporan / balasan","on":"ホウ","kun":"むくいる","strokes":12,"radical":"土","level":"N3","examples":["報告"]},
  {"k":"告","meaning":"memberi tahu","on":"コク","kun":"つげる","strokes":7,"radical":"口","level":"N3","examples":["報告"]},
  {"k":"確","meaning":"pasti / memastikan","on":"カク","kun":"たしか","strokes":15,"radical":"石","level":"N3","examples":["確認"]},
  {"k":"認","meaning":"mengakui / mengenali","on":"ニン","kun":"みとめる","strokes":14,"radical":"言","level":"N3","examples":["確認","認識"]},
];

export const grammar = [
  {"pattern":"です","meaning":"adalah / bentuk sopan","level":"N5","formation":"Noun / な-adjective + です","example":"私は学生です。","translation":"Saya adalah pelajar."},
  {"pattern":"ます","meaning":"akhiran sopan untuk kata kerja","level":"N5","formation":"Verb stem + ます","example":"毎日日本語を勉強します。","translation":"Saya belajar bahasa Jepang setiap hari."},
  {"pattern":"は","meaning":"penanda topik","level":"N5","formation":"Topic + は + informasi","example":"私はインドネシア人です。","translation":"Saya orang Indonesia."},
  {"pattern":"が","meaning":"penanda subjek / fokus","level":"N5","formation":"Subject + が + predicate","example":"猫がいます。","translation":"Ada kucing."},
  {"pattern":"を","meaning":"penanda objek langsung","level":"N5","formation":"Object + を + Verb","example":"パンを食べます。","translation":"Saya makan roti."},
  {"pattern":"に","meaning":"waktu / tujuan / lokasi keberadaan","level":"N5","formation":"Time/Destination + に","example":"七時に起きます。","translation":"Saya bangun pukul tujuh."},
  {"pattern":"で","meaning":"tempat terjadinya aktivitas / alat","level":"N5","formation":"Place/Means + で + Verb","example":"学校で勉強します。","translation":"Saya belajar di sekolah."},
  {"pattern":"へ","meaning":"arah tujuan","level":"N5","formation":"Destination + へ + movement verb","example":"日本へ行きます。","translation":"Saya pergi ke Jepang."},
  {"pattern":"から・まで","meaning":"dari ... sampai ...","level":"N5","formation":"A + から + B + まで","example":"九時から五時まで働きます。","translation":"Saya bekerja dari jam sembilan sampai jam lima."},
  {"pattern":"～たい","meaning":"ingin melakukan","level":"N5","formation":"Verb ます-stem + たい","example":"日本へ行きたいです。","translation":"Saya ingin pergi ke Jepang."},
  {"pattern":"～ながら","meaning":"sambil melakukan","level":"N4","formation":"Verb ます-stem + ながら","example":"音楽を聞きながら勉強します。","translation":"Belajar sambil mendengarkan musik."},
  {"pattern":"～そうです","meaning":"kelihatannya / tampaknya","level":"N4","formation":"Stem / adjective + そうです","example":"この料理はおいしそうです。","translation":"Masakan ini kelihatannya enak."},
  {"pattern":"～と思います","meaning":"saya pikir / menurut saya","level":"N4","formation":"Plain form + と思います","example":"明日は雨が降ると思います。","translation":"Saya pikir besok akan hujan."},
  {"pattern":"～と言います","meaning":"mengatakan bahwa","level":"N4","formation":"Plain form + と言います","example":"先生は『頑張って』と言いました。","translation":"Guru mengatakan 'semangat'."},
  {"pattern":"～たことがある","meaning":"pernah melakukan","level":"N4","formation":"Verb past + ことがある","example":"日本へ行ったことがあります。","translation":"Saya pernah pergi ke Jepang."},
  {"pattern":"～なければならない","meaning":"harus melakukan","level":"N4","formation":"Negative stem + なければならない","example":"宿題をしなければなりません。","translation":"Saya harus mengerjakan PR."},
  {"pattern":"～なくてもいい","meaning":"tidak harus","level":"N4","formation":"Negative stem + なくてもいい","example":"明日は来なくてもいいです。","translation":"Besok tidak harus datang."},
  {"pattern":"～てみる","meaning":"mencoba melakukan","level":"N4","formation":"Verb て-form + みる","example":"この漢字を書いてみます。","translation":"Saya akan mencoba menulis kanji ini."},
  {"pattern":"～ておく","meaning":"melakukan sebagai persiapan","level":"N4","formation":"Verb て-form + おく","example":"旅行の前にホテルを予約しておきます。","translation":"Saya memesan hotel terlebih dahulu sebelum perjalanan."},
  {"pattern":"～ので","meaning":"karena / sebab","level":"N4","formation":"Plain form + ので","example":"雨が降っているので、家にいます。","translation":"Karena sedang hujan, saya berada di rumah."},
  {"pattern":"～ために","meaning":"untuk / demi","level":"N3","formation":"Verb dictionary / Noun + の + ために","example":"日本で働くために、日本語を勉強しています。","translation":"Saya belajar bahasa Jepang untuk bekerja di Jepang."},
  {"pattern":"～によって","meaning":"oleh / tergantung pada / melalui","level":"N3","formation":"Noun + によって","example":"人によって考え方が違います。","translation":"Cara berpikir berbeda tergantung orangnya."},
  {"pattern":"～ように","meaning":"agar / supaya","level":"N3","formation":"Verb plain + ように","example":"忘れないようにメモします。","translation":"Saya mencatat supaya tidak lupa."},
  {"pattern":"～ことになる","meaning":"diputuskan / menjadi ketentuan","level":"N3","formation":"Verb dictionary + ことになる","example":"来月、日本へ行くことになりました。","translation":"Sudah diputuskan bahwa saya akan pergi ke Jepang bulan depan."},
  {"pattern":"～ことにする","meaning":"memutuskan sendiri","level":"N3","formation":"Verb dictionary + ことにする","example":"毎日一時間勉強することにします。","translation":"Saya memutuskan untuk belajar satu jam setiap hari."},
  {"pattern":"～ばかり","meaning":"baru saja / hanya","level":"N3","formation":"Verb past + ばかり","example":"日本に来たばかりです。","translation":"Saya baru saja datang ke Jepang."},
  {"pattern":"～はずです","meaning":"seharusnya / mestinya","level":"N3","formation":"Plain form + はずです","example":"彼はもう着くはずです。","translation":"Dia seharusnya sudah tiba sebentar lagi."},
  {"pattern":"～わけではない","meaning":"bukan berarti bahwa","level":"N3","formation":"Plain form + わけではない","example":"高い物が全部いいわけではありません。","translation":"Bukan berarti semua barang mahal itu bagus."},
  {"pattern":"～に対して","meaning":"terhadap / berlawanan dengan","level":"N3","formation":"Noun + に対して","example":"この問題に対して意見を述べます。","translation":"Saya menyampaikan pendapat terhadap masalah ini."},
  {"pattern":"～について","meaning":"mengenai / tentang","level":"N3","formation":"Noun + について","example":"日本の文化について勉強します。","translation":"Saya belajar tentang budaya Jepang."},
];

export const readings = [
  {"title":"わたしの一日","level":"N5","text":"私は毎朝六時に起きます。朝ご飯を食べて、七時半に家を出ます。学校では日本語を勉強します。午後四時ごろ家に帰ります。","translation":"Saya bangun pukul enam setiap pagi. Setelah sarapan, saya keluar rumah pukul setengah delapan. Di sekolah saya belajar bahasa Jepang. Sekitar pukul empat sore saya pulang."},
  {"title":"週末の予定","level":"N5","text":"土曜日は友達と駅で会います。それから電車で町へ行きます。昼ご飯を食べて、本屋で日本語の本を買います。","translation":"Hari Sabtu saya bertemu teman di stasiun. Setelah itu kami pergi ke kota dengan kereta. Kami makan siang dan membeli buku bahasa Jepang di toko buku."},
  {"title":"日本語の勉強","level":"N5","text":"私は毎日ひらがなとカタカナを練習します。新しい言葉を十個覚えて、短い文を書きます。分からない言葉は辞書で調べます。","translation":"Saya berlatih hiragana dan katakana setiap hari. Saya menghafal sepuluh kata baru dan menulis kalimat pendek. Kata yang tidak saya pahami saya cari di kamus."},
  {"title":"新しい仕事","level":"N4","text":"来週から新しい仕事が始まります。仕事の前に必要な道具を準備して、予定を確認します。分からないことがあれば、先輩に質問します。","translation":"Minggu depan pekerjaan baru dimulai. Sebelum bekerja saya menyiapkan alat yang diperlukan dan memeriksa jadwal. Jika ada yang tidak saya pahami, saya bertanya kepada senior."},
  {"title":"旅行の準備","level":"N4","text":"来月、友達と京都へ旅行する予定です。ホテルはもう予約してあります。旅行の前に行きたい場所を調べて、必要な物を準備しておきます。","translation":"Bulan depan saya berencana bepergian ke Kyoto bersama teman. Hotel sudah dipesan. Sebelum perjalanan saya mencari tempat yang ingin dikunjungi dan menyiapkan barang yang diperlukan."},
  {"title":"日本での生活","level":"N4","text":"日本で生活を始めたとき、電車の使い方が少し難しいと思いました。しかし、毎日使っているうちに慣れてきました。今では一人でも安心して出かけられます。","translation":"Saat mulai hidup di Jepang, saya merasa cara menggunakan kereta sedikit sulit. Namun setelah menggunakannya setiap hari, saya mulai terbiasa. Sekarang saya bisa bepergian sendiri dengan tenang."},
  {"title":"技術と環境","level":"N3","text":"新しい技術は私たちの生活を便利にします。しかし、環境への影響も考える必要があります。生産方法を改善することは、会社にとって大切な課題です。","translation":"Teknologi baru membuat hidup kita lebih nyaman. Namun kita juga perlu memikirkan dampaknya terhadap lingkungan. Memperbaiki metode produksi merupakan tantangan penting bagi perusahaan."},
  {"title":"仕事の改善","level":"N3","text":"工場では品質を安定させるために、毎日の作業内容を確認しています。問題が起きた場合は原因を調べ、チームで改善方法を相談します。その結果を記録し、次の作業に生かします。","translation":"Di pabrik, isi pekerjaan harian diperiksa untuk menjaga kestabilan kualitas. Jika terjadi masalah, penyebabnya dicari dan tim mendiskusikan metode perbaikan. Hasilnya dicatat dan digunakan pada pekerjaan berikutnya."},
  {"title":"学び続ける理由","level":"N3","text":"外国語を身につけるためには、短期間で多く勉強するだけでは十分ではありません。毎日少しずつ続けることが重要です。失敗しても、その原因を確認して次の学習方法を改善すれば、少しずつ成長できます。","translation":"Untuk menguasai bahasa asing, belajar banyak hanya dalam waktu singkat tidak cukup. Yang penting adalah terus belajar sedikit demi sedikit setiap hari. Walaupun gagal, jika penyebabnya diperiksa dan cara belajar berikutnya diperbaiki, kemampuan dapat berkembang sedikit demi sedikit."},
];
