const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='nihongoJourney_v2';
const defaults={xp:0,total:0,correct:0,mastery:{},mistakes:{},lastStudy:null,streak:0};
let state=load(); let materialType='kana'; let quiz=null; let lastQuiz={type:'mixed',level:'all',count:20};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateUI()}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function levelItems(level){if(level==='foundation')return [...HIRAGANA,...KATAKANA];return ALL_ITEMS.filter(x=>x.level===level)}
function mastery(id){return Math.min(5,state.mastery[id]||0)}
function mastered(items){return items.filter(x=>mastery(x.id)>=3).length}
function accuracy(){return state.total?Math.round(state.correct/state.total*100):0}
function go(page){$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+page).classList.add('active-page');$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='path')renderPath();if(page==='library')renderMaterials();if(page==='progress')renderProgress()}
function touchStudy(){const today=new Date();const d=today.toISOString().slice(0,10);if(state.lastStudy===d)return;if(!state.lastStudy)state.streak=1;else{const prev=new Date(state.lastStudy+'T00:00:00');const diff=Math.round((new Date(d+'T00:00:00')-prev)/86400000);state.streak=diff===1?state.streak+1:1}state.lastStudy=d}
function updateUI(){const acc=accuracy(), m=mastered(ALL_ITEMS), rev=Object.keys(state.mistakes).length;$('#headerXP').textContent=state.xp+' XP';$('#homeStreak').textContent=state.streak+' hari';$('#homeXP').textContent=state.xp+' XP';$('#homeAccuracy').textContent=acc+'%';$('#homeMastered').textContent=m+' item';$('#setupReview').textContent=rev;$('#setupMastered').textContent=m;$('#setupAccuracy').textContent=acc+'%';if($('#pXP')){$('#pXP').textContent=state.xp;$('#pAccuracy').textContent=acc+'%';$('#pMastered').textContent=m;$('#pReview').textContent=rev}}
function renderPath(){const levels=[['foundation','基','Fondasi','Hiragana & Katakana'],['N5','N5','Pemula','JLPT N5'],['N4','N4','Dasar lanjut','JLPT N4'],['N3','N3','Menengah','JLPT N3']];$('#pathContainer').innerHTML=levels.map(([level,badge,sub,title])=>{const mods=level==='foundation'?[['Hiragana','あ',HIRAGANA],['Katakana','ア',KATAKANA]]:[['Kosakata','語',VOCAB.filter(x=>x.level===level)],['Kanji','字',KANJI.filter(x=>x.level===level)],['Grammar','文',GRAMMAR.filter(x=>x.level===level)]];return `<section class="path-section"><div class="path-section-head"><div class="level-badge">${badge}</div><div><small>${sub}</small><h2>${title}</h2><p>${mastered(levelItems(level))} dari ${levelItems(level).length} item dikuasai</p></div></div><div class="module-list">${mods.map(([name,icon,items])=>{const p=items.length?Math.round(mastered(items)/items.length*100):0;return `<div class="module-row card" data-module="${name.toLowerCase()}" data-level="${level}"><div class="module-icon">${icon}</div><div><h3>${name}</h3><p>${items.length} item pembelajaran</p></div><div class="module-progress"><strong>${p}%</strong><div class="mini-track"><span style="width:${p}%"></span></div></div></div>`}).join('')}</div></section>`}).join('');$$('.module-row').forEach(r=>r.onclick=()=>{materialType=r.dataset.module.includes('hiragana')||r.dataset.module.includes('katakana')?'kana':r.dataset.module;go('library');setTimeout(()=>{materialType=materialType==='kosakata'?'vocab':materialType;$$('.segment').forEach(b=>b.classList.toggle('active',b.dataset.material===materialType));$('#levelFilter').value=r.dataset.level==='foundation'?'all':r.dataset.level;$('#materialSearch').value=r.dataset.module==='hiragana'?'Hiragana':r.dataset.module==='katakana'?'Katakana':'';renderMaterials()},0)})}
function dots(id){return `<span class="mastery-dots">${[1,2,3,4,5].map(n=>`<i class="${mastery(id)>=n?'on':''}"></i>`).join('')}</span>`}
function renderMaterials(){const q=$('#materialSearch').value.trim().toLowerCase(),level=$('#levelFilter').value;let items=[];if(materialType==='kana')items=[...HIRAGANA,...KATAKANA];if(materialType==='vocab')items=VOCAB;if(materialType==='kanji')items=KANJI;if(materialType==='grammar')items=GRAMMAR;if(level!=='all')items=items.filter(x=>x.level===level);items=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q));$('#materialContent').innerHTML=`<div class="material-grid">${items.map(x=>{if(x.type==='kana')return `<article class="kana-card"><div class="kana-char">${x.char}</div><div class="kana-romaji">${x.romaji} · ${x.script}</div><div class="meta-row"><span class="tag">Fondasi</span>${dots(x.id)}</div></article>`;if(x.type==='vocab')return `<article class="vocab-card"><div class="vocab-word">${x.word}</div><div class="vocab-reading">${x.reading} · ${x.romaji}</div><div class="vocab-meaning">${x.meaning}</div><div class="meta-row"><span class="tag">${x.level} · ${x.category}</span>${dots(x.id)}</div></article>`;if(x.type==='kanji')return `<article class="kanji-card"><div class="kanji-char">${x.char}</div><div class="kanji-reading">${x.reading}</div><div class="kanji-meaning">${x.meaning}</div><div class="meta-row"><span class="tag">${x.level}</span>${dots(x.id)}</div></article>`;return `<article class="grammar-card"><div class="grammar-pattern">${x.pattern}</div><p><strong>${x.functionText}</strong></p><div class="grammar-example">${x.example}<br><span>${x.translation}</span></div><div class="meta-row"><span class="tag">${x.level}</span>${dots(x.id)}</div></article>`}).join('')||'<div class="empty-state">Materi tidak ditemukan.</div>'}</div>`}
function poolByLevel(arr,level){return level==='all'?arr:arr.filter(x=>x.level===level)}
function options(pool,item,key){const vals=shuffle(pool.filter(x=>x.id!==item.id).map(x=>x[key]).filter((x,i,a)=>a.indexOf(x)===i)).slice(0,3);return shuffle([item[key],...vals])}
function qKana(level){const pool=[...HIRAGANA,...KATAKANA],item=pool[Math.floor(Math.random()*pool.length)];return {item,label:'Apa bacaan karakter ini?',main:item.char,sub:item.script,answer:item.romaji,opts:options(pool,item,'romaji'),exp:`${item.char} dibaca “${item.romaji}”.`}}
function qVocabMeaning(level){const pool=poolByLevel(VOCAB,level),item=pool[Math.floor(Math.random()*pool.length)];return {item,label:'Apa arti kosakata ini?',main:item.word,sub:`${item.reading} · ${item.level}`,answer:item.meaning,opts:options(pool,item,'meaning'),exp:`${item.word} (${item.reading}) berarti “${item.meaning}”.`}}
function qVocabReading(level){const pool=poolByLevel(VOCAB,level),item=pool[Math.floor(Math.random()*pool.length)];return {item,label:'Bagaimana cara membacanya?',main:item.word,sub:item.meaning,answer:item.reading,opts:options(pool,item,'reading'),exp:`${item.word} dibaca ${item.reading} (${item.romaji}).`}}
function qKanji(level){const pool=poolByLevel(KANJI,level),item=pool[Math.floor(Math.random()*pool.length)];return {item,label:'Apa arti kanji ini?',main:item.char,sub:item.reading,answer:item.meaning,opts:options(pool,item,'meaning'),exp:`${item.char} (${item.reading}) bermakna “${item.meaning}”.`}}
function qGrammar(level){const pool=poolByLevel(GRAMMAR,level),item=pool[Math.floor(Math.random()*pool.length)];return {item,label:'Apa fungsi pola grammar ini?',main:item.pattern,sub:item.example,answer:item.functionText,opts:options(pool,item,'functionText'),exp:`${item.pattern}: ${item.functionText}. Contoh: ${item.example}`}}
function build(type,level){if(type==='kana')return qKana(level);if(type==='vocab-meaning')return qVocabMeaning(level);if(type==='vocab-reading')return qVocabReading(level);if(type==='kanji-meaning')return qKanji(level);if(type==='grammar')return qGrammar(level);if(type==='review'){const ids=Object.keys(state.mistakes),id=ids[Math.floor(Math.random()*ids.length)],it=ALL_ITEMS.find(x=>x.id===id);if(!it)return build('mixed',level);if(it.type==='kana')return qKana('all');if(it.type==='vocab')return Math.random()<.5?qVocabMeaning(it.level):qVocabReading(it.level);if(it.type==='kanji')return qKanji(it.level);return qGrammar(it.level)}const choices=['kana','vocab-meaning','vocab-reading','kanji-meaning','grammar'];return build(choices[Math.floor(Math.random()*choices.length)],level)}
function startQuiz(type=$('#quizType').value,level=$('#quizLevel').value,count=Number($('#questionCount').value)){lastQuiz={type,level,count};quiz={type,level,count,index:0,correct:0,current:null,answered:false};touchStudy();$('#quizSetup').classList.add('hidden');$('#quizResult').classList.add('hidden');$('#quizGame').classList.remove('hidden');showQ()}
function showQ(){quiz.answered=false;quiz.current=build(quiz.type,quiz.level);const q=quiz.current;$('#quizCounter').textContent=`${quiz.index+1} / ${quiz.count}`;$('#quizScore').textContent=`${quiz.correct} benar`;$('#quizBar').style.width=`${quiz.index/quiz.count*100}%`;$('#questionLabel').textContent=q.label;$('#questionMain').textContent=q.main;$('#questionMain').classList.toggle('text',q.main.length>8);$('#questionSub').textContent=q.sub||'';$('#feedback').className='feedback hidden';$('#nextQuestion').classList.add('hidden');$('#answerGrid').innerHTML=q.opts.map((o,i)=>`<button class="answer-btn" data-answer="${esc(o)}"><span>${String.fromCharCode(65+i)}.</span> ${esc(o)}</button>`).join('');$$('.answer-btn').forEach(b=>b.onclick=()=>answer(b))}
function answer(btn){if(quiz.answered)return;quiz.answered=true;const val=btn.dataset.answer,q=quiz.current,ok=val===q.answer;state.total++;if(ok){quiz.correct++;state.correct++;state.xp+=10;state.mastery[q.item.id]=Math.min(5,mastery(q.item.id)+1);if(state.mistakes[q.item.id]){state.mistakes[q.item.id]--;if(state.mistakes[q.item.id]<=0)delete state.mistakes[q.item.id]}}else{state.mastery[q.item.id]=Math.max(0,mastery(q.item.id)-1);state.mistakes[q.item.id]=(state.mistakes[q.item.id]||0)+1}$$('.answer-btn').forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct');else if(b===btn&&!ok)b.classList.add('wrong')});$('#feedback').className='feedback '+(ok?'good':'bad');$('#feedback').innerHTML=`<strong>${ok?'Benar!':'Belum tepat.'}</strong> ${esc(q.exp)}`;$('#nextQuestion').classList.remove('hidden');save()}
function nextQ(){quiz.index++;if(quiz.index>=quiz.count)return finish();showQ()}
function finish(){const pct=Math.round(quiz.correct/quiz.count*100),gain=quiz.correct*10;$('#quizGame').classList.add('hidden');$('#quizResult').classList.remove('hidden');$('#resultPct').textContent=pct+'%';$('#resultTitle').textContent=pct>=90?'Luar biasa!':pct>=70?'Bagus!':'Terus berlatih!';$('#resultDesc').textContent=`Kamu menjawab ${quiz.correct} dari ${quiz.count} soal dengan benar.`;$('#resultCorrect').textContent=quiz.correct;$('#resultWrong').textContent=quiz.count-quiz.correct;$('#resultXP').textContent='+'+gain;save()}
function renderProgress(){updateUI();const levels=[['Fondasi','foundation'],['JLPT N5','N5'],['JLPT N4','N4'],['JLPT N3','N3']];$('#levelProgressList').innerHTML=levels.map(([name,l])=>{const items=levelItems(l),p=Math.round(mastered(items)/items.length*100);return `<div class="level-progress-row"><strong>${name}</strong><div class="progress-track"><div style="width:${p}%"></div></div><span>${p}%</span></div>`}).join('');const rev=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,15);$('#reviewList').innerHTML=rev.map(([id,n])=>{const x=ALL_ITEMS.find(i=>i.id===id);if(!x)return'';const title=x.char||x.word||x.pattern,sub=x.romaji||x.meaning||x.functionText;return `<div class="review-item"><div><strong>${esc(title)}</strong><br><span>${esc(sub)}</span></div><span>${n}× salah</span></div>`}).join('')||'<div class="empty-state">Belum ada item untuk direview. Bagus!</div>'}
$$('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));$$('[data-open-level]').forEach(b=>b.onclick=()=>go('path'));$$('.segment').forEach(b=>b.onclick=()=>{materialType=b.dataset.material;$$('.segment').forEach(x=>x.classList.toggle('active',x===b));renderMaterials()});$('#levelFilter').onchange=renderMaterials;$('#materialSearch').oninput=renderMaterials;$('#startQuiz').onclick=()=>startQuiz();$('#nextQuestion').onclick=nextQ;$('#retryQuiz').onclick=()=>startQuiz(lastQuiz.type,lastQuiz.level,lastQuiz.count);$('#clearReview').onclick=()=>{state.mistakes={};save();renderProgress()};$$('[data-quick]').forEach(b=>b.onclick=()=>{go('quiz');const m=b.dataset.quick;if(m==='kana'){ $('#quizType').value='kana';$('#quizLevel').value='all'}else if(m==='vocab'){ $('#quizType').value='vocab-meaning';$('#quizLevel').value='all'}else $('#quizType').value='review'});updateUI();renderMaterials();
